export enum Operation {
    OPERATION_NONE = 'OPERATION_NONE',
    OPERATION_SEND_MESSAGE = 'OPERATION_SEND_MESSAGE',
    OPERATION_FILTER = 'OPERATION_FILTER',

    STATUS_SENT = 'STATUS_SENT',
    STATUS_FAILED = 'STATUS_FAILED',
    STATUS_PENDING = 'STATUS_PENDING',
    STATUS_SKIPPED = 'STATUS_SKIPPED',
}